defmodule Rosalind.REVC do
  @moduledoc """
  Complementing a Strand of DNA
  http://rosalind.info/problems/revc/

  Given: A DNA string s of length at most 1000 bp.

  Return: The reverse complement sc of s.
  """

  @doc """
  # Tests

  iex> dataset = "AAAACCCGGT"
  iex> result  = "ACCGGGTTTT"
  iex> assert Rosalind.REVC.process(dataset) == result
  true

  # Dataset 1
  iex> dataset = "AGCTATCTCGGGGAAGGCGTTGTCTGCTGAAAGAGACCTTATTCCCAAAGACTGGTCTGGCGAATACCGGTAGACATCCTAGAAAGAGCTAAGCTTAGGCGAACGACTACCCCACCAGACCAGACGACGACTATGGCCGTTACAGTACCAGTGCCATTTAGACGAAGTAGCTCACGCCAACTAAGTTAGGTGTTGGAGCATCTAGTTGCTAGTGGACCAGACGTGGACAGCGCGCCGAGCGTCGTCTGTCGAGATTGTTTAACGGGGCTGAGGGTTTGACCAGGAGTTTGGCCCTCGTCTGGCCTATGGTGCCACCACCACCGGTCTCGCTCTATTTTCTCTTGCGTATAGTCTCAGAGTTACTACGGCTTTACACATGGTGGCACGAATTGCATCCGCCCTGCTGAACCTTTCACCGCTACATGTGAAGTGCGGGTGAGGAACTTTAGGTGCTAACCCCATCCAACCTCGGTACTCTTAGTTGGTCAGTACTTTAGTAGGCACTTCCCGCGCCTCGCTTCCGCCTCCTGGACACTGACGAAGTCCGGCAATATTGCGTTACACAGTGTTTCAGGCGACTTCAAGGCTGCTGCCTCCCTAACTTCACAGTGACGGAGGTTGACCTGGTCTCAATAGATGGCCCAGTTGGTCGCTGCGGGACTAGTGTCTCCTTCGTGAAACGAGTGAGCACTGGATTGATTGATGCCCACGGCCGTCCCTCCCTCTTACTGTGCAGACGCCAACGTGACGTCGGTCGGGTCAACTAGCGCCTTGGCAGGCATAGCGAGGGTAACGAGCATCCAGTCACGGGGGAATCTATGGCCAATGGGCAGATCCCATAGTTCAATTTGTCACACGGGTATCGTAGCACAGTGCTGCACACCGCTCGATTTAAATCTGGACGCATAAGGGCTGTAGGGACACAAC"
  iex> result  = "GTTGTGTCCCTACAGCCCTTATGCGTCCAGATTTAAATCGAGCGGTGTGCAGCACTGTGCTACGATACCCGTGTGACAAATTGAACTATGGGATCTGCCCATTGGCCATAGATTCCCCCGTGACTGGATGCTCGTTACCCTCGCTATGCCTGCCAAGGCGCTAGTTGACCCGACCGACGTCACGTTGGCGTCTGCACAGTAAGAGGGAGGGACGGCCGTGGGCATCAATCAATCCAGTGCTCACTCGTTTCACGAAGGAGACACTAGTCCCGCAGCGACCAACTGGGCCATCTATTGAGACCAGGTCAACCTCCGTCACTGTGAAGTTAGGGAGGCAGCAGCCTTGAAGTCGCCTGAAACACTGTGTAACGCAATATTGCCGGACTTCGTCAGTGTCCAGGAGGCGGAAGCGAGGCGCGGGAAGTGCCTACTAAAGTACTGACCAACTAAGAGTACCGAGGTTGGATGGGGTTAGCACCTAAAGTTCCTCACCCGCACTTCACATGTAGCGGTGAAAGGTTCAGCAGGGCGGATGCAATTCGTGCCACCATGTGTAAAGCCGTAGTAACTCTGAGACTATACGCAAGAGAAAATAGAGCGAGACCGGTGGTGGTGGCACCATAGGCCAGACGAGGGCCAAACTCCTGGTCAAACCCTCAGCCCCGTTAAACAATCTCGACAGACGACGCTCGGCGCGCTGTCCACGTCTGGTCCACTAGCAACTAGATGCTCCAACACCTAACTTAGTTGGCGTGAGCTACTTCGTCTAAATGGCACTGGTACTGTAACGGCCATAGTCGTCGTCTGGTCTGGTGGGGTAGTCGTTCGCCTAAGCTTAGCTCTTTCTAGGATGTCTACCGGTATTCGCCAGACCAGTCTTTGGGAATAAGGTCTCTTTCAGCAGACAACGCCTTCCCCGAGATAGCT"
  iex> assert Rosalind.REVC.process(dataset) == result
  true

  """
  def process(s) do
    pairs = %{"A" => "T", "C" => "G", "G" => "C", "T" => "A"}
    
    String.reverse(s)
    |> String.graphemes
    |> Enum.map_join("", fn(char) -> Map.get(pairs, char) end)
  end
end